# .github/workflows/rubocop-analysis.yml
name: "RuboCop"

on: [push]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -yqq postgresql-12 postgresql-server-dev-12 libpq-dev     
  
      - name: install do_postgres
        run: gem install do_postgres -- --with-pgsql-server-include=/usr/include/postgresql/12/server

      - name: Install Code Scanning integration
        run: bundle add code-scanning-rubocop --skip-install

      - name: Debugging with tmate
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3.5

      - name: Install dependencies
        run: bundle install

      - name: RuboCop run
        run: |
          bash -c "
            bundle exec rubocop --require code_scanning --format CodeScanning::SarifFormatter -o rubocop.sarif
            [[ $? -ne 2 ]]
          "

      - name: Upload Sarif output
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: rubocop.sarif
